<import name="Tabs" src="tabs.inc" />
<html>
    <head>
        <title>$pagetitle</title>
    </head>
    <body>
        <div>
            <div style="display: flex">
                <img src="/logo" />
                <h1>$pagetitle</h1>
            </div>
            <Tabs heading="top bar tabs"/>
            <slave />
            <Tabs heading="bottom bar tabs"/>
            <p>Your footer here</p>
        </div>
    </body>
</html>